### ISSUE TITLE
--no-inline-includes erroneously drops <style> tags

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-css-build#13]
When an element has more than one `<style>` tags, `--no-inline-includes` causes the first one to be dropped. Example below

`bug.html`
```html
<dom-module id="my-style">
  <template>
    <style>
      :host {
        background-color: red;
      }
    </style>
  </template>
</dom-module>

<dom-module id="my-element">
  <template>
    <style include="my-style"></style>
    <style>
      :host([animating]) {
        background-color: green;
      }
    </style>
  </template>
</dom-module>
```

Then run
```
./node_modules/polymer-css-build/bin/polymer-css-build bug.html -o foo.html --no-inline-includes
```

`foo.html` becomes

```html
<html><head></head><body><dom-module id="my-style" css-build="shadow">
  <template>
    <style scope="my-style">:host {
  background-color: red;
}

</style>
  </template>
</dom-module>

<dom-module id="my-element" css-build="shadow">
  <template>
    
    <style scope="my-element">:host([animating]) {
  background-color: green;
}

</style>
  </template>
</dom-module>
</body></html>
```

Notice how `my-style` is no longer referred by `my-element`.  Omitting `-no-inline-includes` handles it correctly.

```
./node_modules/polymer-css-build/bin/polymer-css-build bug.html -o foo.html
```

```html
<html><head></head><body><dom-module id="my-style" css-build="shadow">
  <template>
    <style scope="my-style">:host {
  background-color: red;
}

</style>
  </template>
</dom-module>

<dom-module id="my-element" css-build="shadow">
  <template>
    
    <style scope="my-element">:host {
  background-color: red;
}

:host([animating]) {
  background-color: green;
}

</style>
  </template>
</dom-module>
</body></html>
```

**Comment by danbeam** [comment]
@azakus

**Comment by danbeam** [comment]
So it seems like during the combination of `<style>` tags part we're not keeping all `include=` attributes while "consuming" the `<style>` tags.  This makes sense as they were previously being processed and left empty after inlining.

We should either:
1. combine all the includes in order while combining
1. leave `<style>`s even more alone and change the flag to like --preserve-style or something?

here's an example of the latter ([PR](https://github.com/Polymer/polymer-css-build/compare/master...danbeam:preserve-style)) which fixes this toy example locally.

**Comment by azakus** [comment]
I favor option 1 as well. Thanks for the PR!

**Comment by azakus** [comment]
Fixed with #14, released as v0.1.1

**Comment by freshp86** [comment]
It would be nice to have some test coverage before closing this bug completely.

**Comment by azakus** [comment]
@freshp86 yeah that's fair, I'll go make one up

**Comment by freshp86** [comment]
Thanks!

**Comment by danbeam** [comment]
btw, closed the other PR.

I agree that tests would be swell.  I was going to write one; just wanted to know which route @azakus wanted to go first.  Now that he's also volunteered to make one up, who am I to stop him :wink:

**Comment by azakus** [comment]
I made some tests, and cleaned up the implementation to actually work  😆

**Comment by freshp86** [comment]
> I made some tests, and cleaned up the implementation to actually work  :laughing:

Thanks. Does this mean that we need v0.1.2 to actually get a working implementation?

**Comment by azakus** [comment]
@freshp86 yes
